version: '3.6'
services:
  frontend:
    image: frontend
    ports:
      - "4200:4200"
    expose:
      - 4200
    build:
      context: ".."
      dockerfile: docker/Dockerfile_frontend
    networks:
      - fwnet
    depends_on:
      - "backend"

  backend:
    image: backend
    ports:
      - "5000:5000"
    env_file:
      - database.env # configure postgres
    expose:
      - 5000
    #volumes:
    #  - data:./backend/data
    build:
      context: ".."
      dockerfile: docker/Dockerfile_backend
    networks:
      - fwnet
    depends_on:
      - "db"
    
  db:
    image: postgres
    env_file:
      - database.env # configure postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - fwnet


networks:
  fwnet:
    driver: bridge

#volumes:
#  data: