FROM ubuntu
WORKDIR app
ADD src ./src/
ADD *.json ./
ADD *.txt ./
ADD *.js ./
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get -y install npm nodejs
RUN npm install

RUN npm link @angular/cli
RUN npm uninstall -g @angular/cli
RUN npm cache clean --force
RUN npm install -g @angular/cli@8.0.6; exit 0

RUN ng --version

EXPOSE 4200
CMD ng serve --host 0.0.0.0