version: '3.6'
services:
  frontend:
    image: frontend
    ports:
      - "4200:4200"
    expose:
      - 4200
    build:
      context: ".."
      dockerfile: docker/Dockerfile_frontend
    networks:
      - fwnet

  backend:
    image: backend
    ports:
      - "5000:5000"
    expose:
      - 5000
    #volumes:
    #  - data:./backend/data
    build:
      context: ".."
      dockerfile: docker/Dockerfile_backend
    networks:
      - fwnet

networks:
  fwnet:
    driver: bridge

#volumes:
#  data: