FROM ubuntu
WORKDIR ./
ADD backend backend/
ADD *.json ./
ADD *.txt ./
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get -y install python3 python3-pip
RUN pip3 install -r requirements.txt
RUN python3 -m spacy download en_core_web_md
EXPOSE 5000
CMD ["python3", "backend/app.py"]